project:
  type: website
  output-dir: docs

website:
  title: "Paul T Allen"
  navbar:
    left:
      - text: "Professional Trajectory"
        href: trajectory.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Professional Activities"
        href: activities.qmd
      - text: "Scholarship"
        href: scholarship.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme: flatly
    toc: true
    toc-title: "On this page"
    toc-location: left
    toc-depth: 2
