---
title: "Professional Activities"
---

_For scholarship-related activities see the [Scholarship](scholarship.qmd) page._


## University of New Mexico - Taos

Formal service:

- 2024-2025: I served as the STEM department representative to the UNM-Taos Curriculum Committee
- 2025: I served as the faculty representative on the search committee that ultimately hired Pilar Robledo to be the Director of the UNM-Taos Center for Academic Success and Achievement.
- 2025-present: I serve as the Vice President of the UNM-Taos Faculty Council.
- 2026-present: I am one of two UNM-Taos faculty senators elected to the UNM Faculty Senate. As part of these duties, I serve on the Branch Campus Community Council.

Informal service:

- 2026-present: I am working with UNM-Taos testing center staff to improve workflow for students with testing accommodations.
- 2025-present: I have assisted with the UNM-Taos Kickstarter II grant.
- 2025-present: I have initiated an effort to coordinate messating from mathematics faculty & advising staff regarding mathematics pathways for students, and have created materials to help with advising.

Professional development:

- 2024-2025: I participated in monthly Math Department professional development activities; participated in the campus-wide _Escala_ program.
- 2025-2026: I facilitated a campus-wide pedagogy reading group that met monthly throughout the year.
- 2025-2026: I attended the [Fall 2025 ArizMATYC conference](https://arizmatyc.org/wp/fall-2025-conference/) and the [Spring 2026 MAA Rocky Mountain Section Meeting](https://www.rockymountain.maa.org/events/2026-section-meeting)

Curriculum Development

- 2025-2026: I was awarded an Open Textbook grant from the UNM OER program to develop a calculus curriculum and online textbook.
- 2025-2026: I wrote a course packet and corresponding website for an activity-based curriculum for the introductory algebra course (Math 100) at UNM-Taos.
- 2025-present: As part of the UNM-Taos Kickstarted II grant, I am working to develop technology modules for our algebra courses.

## Lewis & Clark College

I have been on several faculty committees for the College of Arts & Sciences, including:

- Curriculum Committee for the College of Arts & Sciences, 2016–2022 and 2023–2024. I was committee chair in 2019/2020, 2020/2021, 2021/2022, 2023/2024.
- Faculty Council (an elected panel that advises the Dean), 2019–2021.
- Library & Educational Technology Committee, 2014–2016.
- Admissions & Financial Aid Committee, 2010, 2012.

I have served on several search committees:

- 2023 Physics search
- 2022 Biology search
- 2015–2016 Physics search
- 2013–2014 Sociology & Anthropology Search
- 2013 Graduate School of Education search for Science
- 2011–2012 Sociology & Anthropology Search
- 2010–2011 Physics search

I've also served on several other committees, including the working group that coordinated classroom logistics during covid restrictions (2020), as well as the steering committee for the summer science research program (2011–2019).

## Conference Organizing

- I served as the local organizer for the Pacific Northwest Geometry Seminar when it was held at Lewis & Clark College in 2017 and in 2020.
- I was a co-PI on the Pacific Northwest Geometry Seminar grant, 2019–2022.
- I co-organized a Special Session at the 2021 Mathematical Congress of the Americas.

## Editorial Boards

- Cambridge University Press, Textbook Advisory Board Member, 2021 – present
- Mathematics Association of America, Associate Editor for MAA Press Textbook Series, 2021 – present
