---
title: "Paul T Allen"
---

## About Me

My primary professional identity is as a mathematics teacher. I love teaching mathematics and related subjects, and love helping my students grow.

I maintain a modest, but active, research agenda in mathematics. My primary area of expertise is geometric partial differential equations and their applications to mathematical general relativity.

When not teaching or doing mathematics, I enjoy being outdoors — hiking, paddling, gardening, and cross-country skiing. I also enjoy woodworking, and have made two wooden kayaks.

---

## Professional Trajectory

### Academic positions

**University of New Mexico - Taos (2024 - present)**

- 2024: I joined UNM Taos as an Assistant Professor of Mathematics.

**Lewis & Clark College (2010 - present)**

- 2024: I am currently on leave from Lewis & Clark College.
- 2016: Granted tenure and promoted to Associate Professor.
- 2016: Teaching Fellow for the Teaching Effectiveness Program.
- 2014: Honored as the Teacher of the Year.
- 2010: Joined the Mathematical Sciences Department as an Assistant Professor of Mathematics.

**University of Washington Tacoma (2009)**

- Assistant Professor of Mathematics.

**Albert Einstein Institute, the Max Planck Institute for Gravitational Physics (2007 - 2008)**

- Postdoctoral researcher.

### Education

**University of Oregon**

- 2007: Ph.D. in Mathematics; thesis supervised by James Isenberg.
- 2003: M.S. in Mathematics.

**University of Puget Sound**

- 2001: Bachelor degree with majors in Mathematics and Physics.
- Cum laude; honors in both Mathematics and Physics.

---

## Teaching

### University of New Mexico - Taos

Courses taught include:

- Math 99 Pre-algebra
- Math 100 Introduction to Algebra
- Math 1220 College Algebra
- Math 1430 Applications Calculus I
- Math 1522 Calculus II

### Lewis & Clark College

As a faculty member at a small liberal arts college, I taught a wide variety of courses, ranging from first-year seminars to advanced mathematics classes. Courses taught include:

- Math 103 Perspectives in Mathematics
- Math 131 Calculus I
- Math 132 Calculus II
- Math 233 Calculus III
- Math 225 Linear Algebra
- Math 235 Differential Equations
- Math 282 Modeling Competition Preparation
- Math 305 Partial Differential Equations (formerly titled Calculus IV)
- Math 355 Geometry
- Math 358 Topology
- Math 365 Complex Variables
- Math 441 Real Analysis
- Math 442 Advanced Topics in Analysis & Topology
- CS 171 Computer Science I
- Core 107 Exploration & Discovery II (first-year seminar course)
- Core 121 Numbers (first-year seminar course)

I have also supervised numerous independent study courses on a wide range of topics.

### University of Washington Tacoma

During my short time at UWT, I taught calculus, differential equations, and statistics.

### University of Oregon

While a graduate student at the University of Oregon, I was the instructor of record for a wide variety of 100-level mathematics courses including: college algebra, trigonometry, differential & integral calculus, and calculus for life sciences.

---

## Professional Activities

### Lewis & Clark College

I have been on several faculty committees for the College of Arts & Sciences, including:

- Curriculum Committee for the College of Arts & Sciences, 2016–2022 and 2023–2024. I was committee chair in 2019/2020, 2020/2021, 2021/2022, 2023/2024.
- Faculty Council (an elected panel that advises the Dean), 2019–2021.
- Library & Educational Technology Committee, 2014–2016.
- Admissions & Financial Aid Committee, 2010, 2012.

I have served on several search committees:

- 2023 Physics search
- 2022 Biology search
- 2015–2016 Physics search
- 2013–2014 Sociology & Anthropology Search
- 2013 Graduate School of Education search for Science
- 2011–2012 Sociology & Anthropology Search
- 2010–2011 Physics search

I've also served on several other committees, including the working group that coordinated classroom logistics during covid restrictions (2020), as well as the steering committee for the summer science research program (2011–2019).

### Conference Organizing

- I served as the local organizer for the Pacific Northwest Geometry Seminar when it was held at Lewis & Clark College in 2017 and in 2020.
- I was a co-PI on the Pacific Northwest Geometry Seminar grant, 2019–2022.
- I co-organized a Special Session at the 2021 Mathematical Congress of the Americas.

### Editorial Boards

- Cambridge University Press, Textbook Advisory Board Member, 2021 – present
- Mathematics Association of America, Associate Editor for MAA Press Textbook Series, 2021 – present

---

## Scholarship

Most of my technical mathematical work involves problems in geometric analysis and mathematical general relativity. More specifically, I have worked on theory for solving partial differential equations related to the Einstein equations. I have also supervised a large number of undergraduate projects.

### Projects with undergraduate students

I have supervised projects for undergraduate students on these topics:

- **Reaction-diffusion equations.** I have supervised several projects related to numerical simulations of reaction-diffusion equations. Alison and Jenny completed a fun project on the Belousov-Zhabotinsky reaction. Sarah and Nuzhat both completed projects related to the FRAP imaging method.

- **Discrete analogs of differential equations.** I have supervised two different projects related to discretizations of differential equations. Karlie and Sara worked on a project that established solutions to boundary value problems via discrete approximations. Eli and Mack studied flows of polygons that are semi-discrete analogs of the curve shortening flow.

- **Parabolic geometric flows.** I have supervised two different projects related to parabolic geometric flows. Katie and Adam worked on the curve shortening flow subject to Dirichlet boundary conditions. Colin worked on a variant of the curve shortening flow arising from rotationally-symmetric mean curvature flow.

### Papers

- Paul T. Allen, John M. Lee, and David Maxwell. Sobolev-class asymptotically hyperbolic manifolds and the Yamabe problem. *Under review.* <https://arxiv.org/abs/2206.12854>

- Paul T. Allen, James Isenberg, John M. Lee and Iva Stavrov Allen. Asymptotic Gluing of Shear-Free Hyperboloidal Initial Data Sets. [*Annales Henri Poincaré* (2021)](https://rdcu.be/ccV68). <https://arxiv.org/abs/1912.02839>

- Paul T. Allen. Boundary Value Problems and Finite Differences. [*College Math Journal* 47 (2016), no. 1, 34–41](https://www.maa.org/press/periodicals/college-mathematics-journal/the-college-mathematics-journal).

- Paul T. Allen, James Isenberg, John M. Lee, Iva Stavrov Allen. The shear-free condition and constant-mean-curvature hyperboloidal initial data. [*Classical and Quantum Gravity*, Volume 33, Number 11](http://iopscience.iop.org/article/10.1088/0264-9381/33/11/115015). [arXiv:1506.06090](http://arxiv.org/abs/1506.06090)

- Paul T. Allen and Iva Stavrov Allen. Smoothly compactifiable shear-free hyperboloidal data is dense in the physical topology. [*Annales Henri Poincaré* (2017) 18: 2789](https://doi.org/10.1007/s00023-017-0565-2). [arXiv:1506.05842](http://arxiv.org/abs/1506.05842)

- Paul T. Allen, James Isenberg, John M. Lee, Iva Stavrov Allen. Weakly asymptotically hyperbolic manifolds. [*Communications in Analysis and Geometry*, Volume 26 (2018), Number 1](http://www.intlpress.com/site/pub/pages/journals/items/cag/content/vols/0026/0001/a001/index.html). [arXiv:1506.03399](http://arxiv.org/abs/1506.03399)

- Paul T. Allen, Adam Layne, Katharine Tsukahara. The Dirichlet problem for curve shortening flow. (unpublished) [arXiv:1208.3510](http://arxiv.org/abs/1208.3510)

- Paul T. Allen, Lars Andersson, Alvaro Restuccia. Local well-posedness for membranes in the light cone gauge. *Comm. Math. Phys.* 301 (2011), no. 2, 383–410. <http://arxiv.org/abs/0910.1488>

- Paul T. Allen, Alan D. Rendall. Asymptotics of linearized cosmological perturbations. *J. Hyperbolic Differ. Equ.* 7 (2010), no. 2, 255–277. <http://arxiv.org/abs/0906.2517>

- Paul T. Allen, Adam Clausen, James Isenberg. Near-constant mean curvature solutions of the Einstein constraint equations with non-negative Yamabe metrics. *Classical Quantum Gravity* 25 (2008), no. 7, 075009, 15 pp. <http://arxiv.org/abs/0710.0725>

- Paul T. Allen, Lars Andersson, James Isenberg. Timelike minimal submanifolds of general co-dimension in Minkowski space time. *J. Hyperbolic Differ. Equ.* 3 (2006), no. 4, 691–700. <http://arxiv.org/abs/math/0512036>

### Recent presentations

- September 2023: Talk at [Simons Center workshop "Mass, the Einstein Constraint Equations, and the Penrose Inequality Conjecture"](https://scgp.stonybrook.edu/archives/39191)
- April 2023: Talk at the American Physical Society April Meeting session "Geometric Analysis and General Relativity"
- March 2020: Local organizer for the [Pacific Northwest Geometry Seminar](https://sites.math.washington.edu/~lee/PNGS/2020-spring/index.html)
- October 2019: Geometric Analysis Seminar at University of Oregon
- February 2019: Oregon Liberal Arts Mathematics Colloquium at Linfield College
- January 2019: Colloquium and Topology-Geometry Seminar at [Oregon State University](https://math.oregonstate.edu/)
- January 2018: Talk in [AMS Special Session on Mathematical Relativity and Geometric Analysis](http://jointmathematicsmeetings.org/meetings/national/jmm2018/2197_program_ss72.html) at JMM
- October 2017: Talk at [Pacific University](https://www.pacificu.edu/future-undergraduates/academics/areas-study/mathematics)
- March 2017: Talk at the [Charleston AMS](http://www.ams.org/meetings/sectional/2228_program_ss20.html) meeting
- February 2017: Short talk to math students at Lewis & Clark
- July 2016: Talk at BIRS workshop "[Geometric Analysis and General Relativity](http://www.birs.ca/events/2016/5-day-workshops/16w5054)"
- March 2016: Colloquium at University of Connecticut
- January 2016: Short talk at the Joint Math Meetings
- Summer 2015: [Mathematisches Forschungsinstitut Oberwolfach](http://www.mfo.de/)
- Spring 2015: Lewis & Clark Physics Colloquium
- Fall 2014: Seattle University Mathematics Colloquium
- Summer 2014: University of Science & Technology of China, [Geometric Analysis and Relativity](http://math.ustc.edu.cn/Conference/2014gar/index.html)
- Spring 2014: Willamette University Physics Colloquium

---

## Contact Information

### University of New Mexico - Taos

Paul T Allen
STEM Department, MSC 12 7250
University of New Mexico - Taos
1157 County Road 110
Ranchos De Taos, NM 87557 USA

[paultallen \[at\] unm \[dot\] edu](mailto:paultallen@unm.edu)

### Lewis & Clark College

Paul T. Allen
Department of Mathematical Sciences, MSC 110
Lewis and Clark College
615 S. Palatine Hill Road
Portland, OR 97219 USA

Lewis & Clark email: [ptallen \[at\] lclark \[dot\] edu](mailto:ptallen@lclark.edu)
