---
title: "Professional Trajectory"
---

## Academic Positions

### University of New Mexico - Taos

- 2024-present: Assistant Professor of Mathematics.

### Lewis & Clark College

- 2024-present: I am currently on leave from Lewis & Clark College.
- 2016: Granted tenure and promoted to Associate Professor.
- 2016: Teaching Fellow for the Teaching Effectiveness Program.
- 2014: Honored as the Teacher of the Year.
- 2010: Joined the Mathematical Sciences Department as an Assistant Professor of Mathematics.

### University of Washington Tacoma

- 2009: Assistant Professor of Mathematics.

### Albert Einstein Institute, the Max Planck Institute for Gravitational Physics

- 2007-2008: Postdoctoral researcher.

## Education

### University of Oregon

- 2007: Ph.D. in Mathematics; thesis supervised by James Isenberg.
- 2003: M.S. in Mathematics.

### University of Puget Sound

- 2001: Bachelor degree with majors in Mathematics and Physics.
- Cum laude; honors in both Mathematics and Physics.
